services:
  app:
    build: .
    container_name: web-app
    expose:
      - "8000"
    environment:
      THIS_HOST: ${THIS_HOST}
      THIS_PORT: ${THIS_PORT}
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      LOCAL_SERVER: ${LOCAL_SERVER}
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
      SECRET_KEY: ${SECRET_KEY}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front:/usr/share/nginx/html/static:ro
    depends_on:
      - app
    restart: unless-stopped