services:
  app:
    build: .
    container_name: webb-app
    ports:
      - '${THIS_PORT}:${THIS_PORT}'
    environment:
      THIS_HOST: ${THIS_HOST}
      THIS_PORT: ${THIS_PORT}
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      LOCAL_SERVER: ${LOCAL_SERVER}
      GATEWAY_HOST: ${GATEWAY_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
      SECRET_KEY: ${SECRET_KEY}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "442:442"